# -*- coding: utf-8 -*-
"""data_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tis703eue5w-QOrL7D7vGHPYbYv6n7TK
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("synthetic_medical_data.csv")  # datamız
df.head()

#Veri Temizleme Planı
from sklearn.model_selection import train_test_split
import pandas as pd

# 1️⃣ Sayısal sütunları median ile doldur
num_cols = df.select_dtypes(exclude='object').columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

# 2️⃣ Kategorik sütunları "Missing" ile doldur
cat_cols = df.select_dtypes(include='object').columns
df[cat_cols] = df[cat_cols].fillna("Missing")

# 3️⃣ One-hot encoding (kategorik değişkenleri sayıya çevir)
df_encoded = pd.get_dummies(df, drop_first=True)

# 4️⃣ Bağımsız değişkenler (X) ve hedef (y)
X = df_encoded.drop("Dead", axis=1)
y = df_encoded["Dead"]

# 5️⃣ Veriyi ayır
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("✅ Train:", X_train.shape, " Test:", X_test.shape)
print("Örnek sınıf oranı:", y.value_counts(normalize=True).round(3))

